### ISSUE TITLE
Dont working...

### ISSUE THREAD

**Issue by MrBearLoL** [Jannyboy11/CustomRecipes#9] opened 2017-08-19 14:53 UTC
No errors in console, i use spigot 1.12.1 my problem is when i create a recipe, and i close the menu, then i can't click furnace or crafting table and 10-20 seconds later the server stop because: timed out... And i dont know how i create a recipe, when i type /addrecipe shaped test this command is open a menu, i place the materials in the table, and then? dont have other button to accept recipe, and dont have place to i place the crafted item... (sorry bad english)

**Comment by Jannyboy11** [comment] 2017-08-20 19:40
Did you shift-click while the inventory was open? It is a [known issue](https://hub.spigotmc.org/jira/browse/SPIGOT-3500) in CraftBukkit/Spigot itself, not a bug in my plugin. md_5 and I [are working on a fix](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/79e55b6dcf6448d33465b936ebdb2cc8a3cf2383#src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java).

**Comment by Jannyboy11** [comment] 2017-08-23 08:05
The shiftclick issue is [now fixed](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/79e55b6dcf6448d33465b936ebdb2cc8a3cf2383#src/main/java/org/bukkit/craftbukkit/entity/CraftHumanEntity.java) in CraftBukkit. If you tell me whether you shiftclicked or not, I can close this issue

**Closed as completed** 2017-09-09 12:19 UTC
